[Distribution]
Distribution=debian
Release=stable

[Output]
Format=disk
OutputSize=50G
ImageId=cbl-builder-vm

[Build]
WithNetwork=yes

[Include]
Include=mkosi-vm

[Content]
Autologin=yes
Bootable=yes
Locale=C.UTF-8
Hostname=cbl-builder-vm
KernelCommandLine=console=ttyS0,115200n8
Packages=
        # Base packages
        apt
        ca-certificates
        curl
        locales
        systemd-repart
        systemd-sysv
        systemd-timesyncd
        openssh-client
        openssh-server
        vim
        # Docker
        containerd.io
        docker-buildx-plugin
        docker-ce
        docker-ce-cli
        docker-compose-plugin
        # actions-runner
        libicu76
        liblttng-ust1t64
RootPassword=hashed:$6$FNuPk1WCVMJvc5WR$pDoitxY8XBRI/GphT2N/VwePy0.tUx6oxVIGKrMy5N9vOKpsdp/qcRzTgGXFX7jjNmVJVY6D6gSuCtByiqXr91
Timezone=America/Los_Angeles
