[Distribution]
Distribution=debian
Release=trixie

[Output]
Format=disk

[Build]
WithNetwork=yes

[Include]
Include=mkosi-vm

[Content]
Autologin=yes
Bootable=yes
Locale=C.UTF-8
KernelCommandLine=console=ttyS0,115200n8
Packages=
        # base
        apt
        ca-certificates
        curl
        locales
        systemd-container
        systemd-repart
        systemd-sysv
        systemd-timesyncd
        openssh-client
        openssh-server
        zstd
        # interactive usage
        btop
        duf
        fd-find
        fish
        tmux
        vim
        # podman
        aardvark-dns
        catatonit
        containers-storage
        crun
        dbus-user-session
        nftables
        passt
        podman
        uidmap
RootPassword=hashed:$6$FNuPk1WCVMJvc5WR$pDoitxY8XBRI/GphT2N/VwePy0.tUx6oxVIGKrMy5N9vOKpsdp/qcRzTgGXFX7jjNmVJVY6D6gSuCtByiqXr91
Timezone=America/Los_Angeles
