[Distribution]
Release=unstable

[Output]
ImageId=ci3-kernel-build-env

[Content]
Packages=
        bc
        binutils-dev
        binutils-powerpc64le-linux-gnu
        bison
        bsdextrautils
        bzip2
        cpio
        device-tree-compiler
        dwarves
        flex
        gawk
        libdw-dev
        libelf-dev
        libssl-dev
        libxml2
        libxxhash-dev
        lz4
        make
        qemu-system
        rsync
        u-boot-tools
        uuid-dev
