# Run a bunch of lint checks to keep me honest
name: Linting
on:
  push:
  workflow_dispatch:
enable-email-notifications: true
jobs:
  python:
    strategy:
      fail-fast: false
      matrix:
        version: ['3.15', '3.14', '3.13']
    uses: nathanchance/actions-workflows/.forgejo/workflows/python_lint.yml@main
    with:
      python_version: ${{ matrix.version }}
  shellcheck:
    uses: nathanchance/actions-workflows/.forgejo/workflows/shellcheck.yml@main
  shfmt:
    uses: nathanchance/actions-workflows/.forgejo/workflows/shfmt.yml@main
