[Distribution]
Distribution=debian

[Output]
Format=oci

[Build]
WithNetwork=yes

[Content]
Bootable=no
Locale=C.UTF-8
Packages=
        # base
        apt
        bash
        ca-certificates
        curl
        git
        gzip
        libc6
        libgcc-16-dev
        libgcc-s1
        libicu[0-9]+$
        liblzma5
        libstdc++6
        libzstd1
        locales
        python3
        tar
        wget
        xz-utils
        zlib1g
        zstd
        # kernel (will also be used by tc-build)
        bc
        binutils-dev
        binutils-powerpc64le-linux-gnu
        bison
        bsdextrautils
        bzip2
        cpio
        device-tree-compiler
        flex
        gawk
        libdw-dev
        libelf-dev
        libssl-dev
        libxxhash-dev
        lz4
        make
        rsync
        u-boot-tools
        uuid-dev
RootPassword=hashed:
RootShell=/bin/bash
