[Distribution]
Distribution=debian
Release=unstable

[Output]
Format=oci
ImageId=cbl-ci3-build-env

[Build]
WithNetwork=yes

[Content]
Bootable=no
Locale=C.UTF-8
Packages=
        apt
        bash
        bc
        binutils-dev
        binutils-powerpc64le-linux-gnu
        bison
        bsdextrautils
        bzip2
        ca-certificates
        cpio
        curl
        device-tree-compiler
        dwarves
        flex
        gawk
        git
        gzip
        libc6
        libdw-dev
        libelf-dev
        libgcc-16-dev
        libgcc-s1
        libicu[0-9]+$
        liblzma5
        libssl-dev
        libstdc++6
        libxml2
        libxxhash-dev
        libzstd1
        locales
        lz4
        make
        python3
        qemu-system
        rsync
        tar
        u-boot-tools
        uuid-dev
        wget
        xz-utils
        zlib1g
        zstd
RootPassword=hashed:
RootShell=/bin/bash
