[Distribution]
Distribution=debian

[Output]
Format=oci

[Build]
WithNetwork=yes

[Content]
Bootable=no
Locale=C.UTF-8
Packages=
        apt
        bash
        ca-certificates
        curl
        git
        gzip
        libc6
        libgcc-16-dev
        libgcc-s1
        libicu[0-9]+$
        liblzma5
        libstdc++6
        libzstd1
        locales
        python3
        tar
        wget
        xz-utils
        zlib1g
        zstd
RootPassword=hashed:
RootShell=/bin/bash
