[core]
toplevel = /srv/git
manifest = ${toplevel}/manifest.js.gz
log = /var/log/grokmirror/main.log
loglevel = info
objstore = ${toplevel}/objstore

[remote]
site = https://git.kernel.org
manifest = ${site}/manifest.js.gz

[pull]
include = /pub/scm/linux/kernel/git/torvalds/linux.git
          /pub/scm/linux/kernel/git/next/linux-next.git
          /pub/scm/linux/kernel/git/stable/linux.git
pull_threads = 5
refresh = 600
