name: build and push runner container images
on:
  pull_request:
    paths:
      - .github/workflows/build_container.yml
      - runner/env
      - runner/build_container_image.sh
      - runner/push_container_image.sh
  push:
    paths:
      - .github/workflows/build_container.yml
      - runner/env
      - runner/build_container_image.sh
      - runner/push_container_image.sh
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Push image to ghcr.io'
        required: false
        type: boolean

jobs:
  build_and_push_kernel_container_image:
    name: Build and push runner container images
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7

      - name: Setup mkosi
        uses: systemd/mkosi@main

      - name: Build kernel container image
        run: runner/build_container_image.sh kernel

      - name: Push kernel container image
        if: ${{ github.repository_owner == 'nathanchance' && ((github.event_name == 'workflow_dispatch' && github.event.inputs.push_image == 'true') || github.event_name == 'schedule') }}
        run: runner/push_container_image.sh kernel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
