# Run linters on code in repo
# * shellcheck and shfmt for shell scripts
# * various tools for Python scripts
name: Lint checks
on: [push, pull_request]
jobs:
  python:
    strategy:
      fail-fast: false
      matrix:
        version: ['3.15', '3.14', '3.13']
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/python_lint.yml@main
    with:
      python_version: ${{ matrix.version }}
      ty: true
      pylint: false
  shellcheck:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shellcheck.yml@main
  shfmt:
    uses: ClangBuiltLinux/actions-workflows/.github/workflows/shfmt.yml@main
